[build]
builder = "NIXPACKS"
buildCommand = "npm --cache /tmp/npm-cache ci && npm --cache /tmp/npm-cache run build"

[deploy]
startCommand = "npm run start -- -p $PORT -H 0.0.0.0"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
